### ISSUE TITLE
Changes language

### ISSUE THREAD

**Issue by mcphendriks** [TessaViergever/connect-your-tribe-profile-card-sprint-7#1]
https://github.com/TessaViergever/connect-your-tribe-profile-card-sprint-7/blob/4f02f192931e552925705ddb29b5ffc3cd5ac523/views/partials/head.ejs#L2

Je pagina wordt geschreven in nl, verander dit even :)

**Comment by TessaViergever** [comment]
Dit is code uit sprint 1, in evt. nieuwe code ga ik dit aanpassen. (:
