### ISSUE TITLE
Maybe you want to put these items in a <nav>.

### ISSUE THREAD

**Issue by Siem-P** [TessaViergever/connect-your-tribe-profile-card-sprint-7#2]
https://github.com/TessaViergever/connect-your-tribe-profile-card-sprint-7/blob/4f02f192931e552925705ddb29b5ffc3cd5ac523/views/index.ejs#L54-L70

**Comment by TessaViergever** [comment]
Dit is code uit sprint 1, in evt. nieuwe code ga ik dit toepassen. (:
