### ISSUE TITLE
Gebruik een svg voor icons

### ISSUE THREAD

**Issue by mcphendriks** [TessaViergever/connect-your-tribe-profile-card-sprint-7#3]
https://github.com/TessaViergever/connect-your-tribe-profile-card-sprint-7/blob/4f02f192931e552925705ddb29b5ffc3cd5ac523/views/index.ejs#L56

**Comment by TessaViergever** [comment]
Dit is code uit sprint 1, in evt. nieuwe code ga ik dat zeker doen! (:
