### ISSUE TITLE
Volgens mij gaat hier iets mis

### ISSUE THREAD

**Issue by KrijnHoetmer** [TessaViergever/connect-your-tribe-profile-card-sprint-7#6]
Hebben we het even over gehad, fix staat volgens mij al klaar :)

https://github.com/TessaViergever/connect-your-tribe-profile-card-sprint-7/blob/4f02f192931e552925705ddb29b5ffc3cd5ac523/views/index.ejs#L10

**Comment by TessaViergever** [comment]
Correct. Heb ik aangepast en gaat nu goed! (:
`<h1><%= member.name %> <%= member.surname %></h1>`
